title: Data Science Portfolio
description: Documenting my learning in Data Structures
theme: jekyll-theme-minimal
show_downloads: false
github:
  is_project_page: false
social_links:
  github: https://github.com/yourusername
  linkedin: https://linkedin.com/in/yourprofile
